version: "3"

services:
  etcd:
    image: quay.io/coreos/etcd:v3.4.13
    container_name: etcd
    ports:
      - 2379:2379
      - 2380:2380
    environment:
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: http://127.0.0.1:2379
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
